### PR TITLE
Blockified POPAnimationDelegate

### PR DESCRIPTION
**Pull request by b3ll**
... because blocks are awesome! :D 

Not 100% sure on the naming animationDid vs. completion though

### CODE REVIEW

**Comment by kimon** [comment]
looks great. matching the delegate names is the right move.

:+1:

**Comment by kimon** [comment]
Would be good to get some unit tests!

**Comment by b3ll** [comment]
Do we want the same for delegate calls?

**Comment by b3ll** [comment]
ah. nvm I see, will do that tomorrow!

**Pull request merged**
