### PR TITLE
Generate coverage stats using slather/Coveralls

### PR DESCRIPTION
**Pull request by Daniel1of1**
- Modify scheme to test with GCOV profile
- Add steps to .travis.yml to install slather and run after
- add .slather.yml to send data to Coveralls
- Update podfile (.36 :smile: )

As per @modocache's [tweet](https://twitter.com/modocache/status/590236557933678592)

Will require turning on this repo on in coveralls.io - coveralls of [Daniel1of1/pop](https://coveralls.io/r/Daniel1of1/pop) for reference.

### CODE REVIEW

**Comment by Daniel1of1** [comment]
error was on `brew update` :confounded: seemed ok on merge on my [fork](https://travis-ci.org/Daniel1of1/pop/builds/59315519)

**Comment by grp** [comment]
Awesome, thanks for the pull request! Weird failures on the Travis build...

I think @kimon owns the Travis setup so would probably be best to setup Coveralls too?

**Comment by modocache** [comment]
Setting up Travis is as easy as toggling a button, so I went ahead and did so for facebook/pop: https://coveralls.io/r/facebook/pop :wink: 

Repository owners should be able to retry the Travis build. I'm thinking it's a Travis failure?

**Comment by facebook-github-bot-1** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Pull request closed without merging**
