### PR TITLE
Add Swift usage examples to README.md

### LINKED ISSUE #324: READ ME in Swift
It'd be a lot easier for those who learned Swift from the beginning of iOS development to understand the usage.

### PR DESCRIPTION
**Pull request by knickmack**
Resolve #324 by adding Swift 3 usage examples alongside Objective-C usage examples.

### CODE REVIEW

**Comment by shahzeb1** [comment]
This is rad. Thanks for this.

**Comment by b3ll** [comment]
wow super sorry about taking so long to see this. Mind if we just update the readme to have something like:

#### Objective-C
// codes

#### Swift
// codes

Thanks for doing this!

**Comment by knickmack** [comment]
Yeah, absolutely no problem

**Comment by b3ll** [comment]
Oh I can happily do it, just wanted to give you the opportunity to do it first :D

**Pull request merged**
